echo "Now is compute-0-36..."
rocks run host compute-0-36 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-37..."
rocks run host compute-0-37 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-38..."
rocks run host compute-0-38 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-39..."
rocks run host compute-0-39 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-40..."
rocks run host compute-0-40 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-41..."
rocks run host compute-0-41 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-43..."
rocks run host compute-0-43 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-44..."
rocks run host compute-0-44 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-45..."
rocks run host compute-0-45 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-46..."
rocks run host compute-0-46 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-47..."
rocks run host compute-0-47 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-49..."
rocks run host compute-0-49 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-51..."
rocks run host compute-0-51 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-52..."
rocks run host compute-0-52 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-53..."
rocks run host compute-0-53 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-54..."
rocks run host compute-0-54 "bash /usr/clean_dfs.sh"
echo "Now is compute-0-42..."
rocks run host compute-0-42 "bash /usr/clean_dfs.sh"
# echo "Now is compute-0-17..."
#rocks run host compute-0-17 "bash /usr/clean_dfs.sh"
# echo "Now is compute-0-18..."
#rocks run host compute-0-18 "bash /usr/clean_dfs.sh"
# echo "Now is compute-0-19..."
# rocks run host compute-0-19 "bash /usr/clean_dfs.sh"
# echo "Now is compute-0-20..."
# rocks run host compute-0-20 "bash /usr/clean_dfs.sh"
# echo "Now is compute-0-21..."
# rocks run host compute-0-21 "bash /usr/clean_dfs.sh"
