scp clean_dfs.sh root@compute-0-36:/usr/
scp clean_dfs.sh root@compute-0-37:/usr/
scp clean_dfs.sh root@compute-0-38:/usr/
scp clean_dfs.sh root@compute-0-39:/usr/
scp clean_dfs.sh root@compute-0-40:/usr/
scp clean_dfs.sh root@compute-0-41:/usr/
scp clean_dfs.sh root@compute-0-42:/usr/
scp clean_dfs.sh root@compute-0-43:/usr/
scp clean_dfs.sh root@compute-0-44:/usr/
scp clean_dfs.sh root@compute-0-45:/usr/
scp clean_dfs.sh root@compute-0-46:/usr/
scp clean_dfs.sh root@compute-0-47:/usr/
scp clean_dfs.sh root@compute-0-48:/usr/
scp clean_dfs.sh root@compute-0-49:/usr/
scp clean_dfs.sh root@compute-0-50:/usr/
scp clean_dfs.sh root@compute-0-51:/usr/
scp clean_dfs.sh root@compute-0-52:/usr/
scp clean_dfs.sh root@compute-0-53:/usr/
scp clean_dfs.sh root@compute-0-54:/usr/
scp clean_dfs.sh root@compute-0-55:/usr/

#scp clean_dfs.sh root@compute-0-27:/usr/
#scp clean_dfs.sh root@compute-0-28:/usr/
#scp clean_dfs.sh root@compute-0-29:/usr/
#scp clean_dfs.sh root@compute-0-30:/usr/
#scp clean_dfs.sh root@compute-0-31:/usr/
#scp clean_dfs.sh root@compute-0-32:/usr/
#scp clean_dfs.sh root@compute-0-33:/usr/
#scp clean_dfs.sh root@compute-0-34:/usr/
#scp clean_dfs.sh root@compute-0-35:/usr/
